In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# 데이터 로드
path = '/content/drive/MyDrive/Colab Notebooks/AI_class/2_week/breast_cancer.csv'
df = pd.read_csv(path)

In [ ]:
# X, y 분리
y = df['label']
X = df.drop('label', axis=1)

In [ ]:
# 학습 / 테스트 분리 (75% / 25%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [ ]:
# ── 1. Logistic Regression ──────────────────────────
clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)

# ── 2. Decision Tree ────────────────────────────────
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)
pred_dt = clf_dt.predict(X_test)

# ── 3. Random Forest ────────────────────────────────
clf_rf = RandomForestClassifier(random_state=0, n_estimators=100)
clf_rf.fit(X_train, y_train)
pred_rf = clf_rf.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# ── 결과 출력 ────────────────────────────────────────
models = {
    "Logistic Regression": pred_lr,
    "Decision Tree":       pred_dt,
    "Random Forest":       pred_rf,
}

for name, pred in models.items():
    print(f"\n--- {name} ---")
    print(f"Accuracy : {accuracy_score(y_test, pred):.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, pred)}")


--- Logistic Regression ---
Accuracy : 0.9720
Confusion Matrix:
[[52  1]
 [ 3 87]]

--- Decision Tree ---
Accuracy : 0.8951
Confusion Matrix:
[[49  4]
 [11 79]]

--- Random Forest ---
Accuracy : 0.9790
Confusion Matrix:
[[52  1]
 [ 2 88]]
