In [3]:
###############################################################################
# Wine - Classification (Accuracy + Confusion Matrix)
# 모델: Logistic Regression, Decision Tree, Random Forest, KNN
###############################################################################

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_wine

In [4]:
# ============================================================================
# 1. 데이터 불러오는 방식 3가지
# ============================================================================

# --- 방법 1: sklearn 내장 데이터셋 ---
wine = load_wine()
X1 = wine.data
y1 = wine.target
print("방법 1 (sklearn 내장):", X1.shape, y1.shape)

# --- 방법 2: csv 저장 후 pd.read_csv ---
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target
df.to_csv('wine.csv', index=False)

wine_csv = pd.read_csv('wine.csv')
X2 = wine_csv.drop('target', axis=1).values
y2 = wine_csv['target'].values
print("방법 2 (csv 저장→읽기):", X2.shape, y2.shape)

# --- 방법 3: URL에서 직접 불러오기 ---
try:
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
    col_names = ['target'] + list(wine.feature_names)  # UCI wine: 첫 열이 class
    wine_web = pd.read_csv(url, header=None, names=col_names)
    X3 = wine_web.drop('target', axis=1).values
    y3 = wine_web['target'].values
    print("방법 3 (URL 직접):", X3.shape, y3.shape)
except Exception as e:
    print(f"방법 3 (URL 직접): 네트워크 오류 - {e}")


방법 1 (sklearn 내장): (178, 13) (178,)
방법 2 (csv 저장→읽기): (178, 13) (178,)
방법 3 (URL 직접): (178, 13) (178,)


In [6]:
# X, y 분리
y = df['target']
X = df.drop('target', axis=1)

In [7]:
# 학습 / 테스트 분리 (75% / 25%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [8]:
# ── 1. Logistic Regression ──────────────────────────
clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)

# ── 2. Decision Tree ────────────────────────────────
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)
pred_dt = clf_dt.predict(X_test)

# ── 3. Random Forest ────────────────────────────────
clf_rf = RandomForestClassifier(random_state=0, n_estimators=100)
clf_rf.fit(X_train, y_train)
pred_rf = clf_rf.predict(X_test)

# ── 4. KNN ──────────────────────────────────────────
clf_knn = KNeighborsClassifier(n_neighbors=5)
clf_knn.fit(X_train, y_train)
pred_knn = clf_knn.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:

# ── 결과 출력 ────────────────────────────────────────
models = {
    "Logistic Regression": pred_lr,
    "Decision Tree":       pred_dt,
    "Random Forest":       pred_rf,
    "KNN":                 pred_knn,
}

for name, pred in models.items():
    print(f"\n--- {name} ---")
    print(f"Accuracy : {accuracy_score(y_test, pred):.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, pred)}")


--- Logistic Regression ---
Accuracy : 0.9333
Confusion Matrix:
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

--- Decision Tree ---
Accuracy : 0.9333
Confusion Matrix:
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

--- Random Forest ---
Accuracy : 0.9778
Confusion Matrix:
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]

--- KNN ---
Accuracy : 0.7333
Confusion Matrix:
[[14  1  1]
 [ 0 17  4]
 [ 3  3  2]]
