In [6]:
###############################################################################
# Iris - Classification (Accuracy)
# 모델: Logistic Regression, Decision Tree, Random Forest, KNN
###############################################################################

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris


In [3]:
# ============================================================================
# 1. 데이터 불러오는 방식 3가지
# ============================================================================

# --- 방법 1: sklearn 내장 데이터셋 ---
iris = load_iris()
X1 = iris.data
y1 = iris.target
print("방법 1 (sklearn 내장):", X1.shape, y1.shape)

# --- 방법 2: csv 저장 후 pd.read_csv ---
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df.to_csv('iris.csv', index=False)

iris_csv = pd.read_csv('iris.csv')
X2 = iris_csv.drop('target', axis=1).values
y2 = iris_csv['target'].values
print("방법 2 (csv 저장→읽기):", X2.shape, y2.shape)

# --- 방법 3: URL에서 직접 불러오기 ---
try:
    url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
    iris_web = pd.read_csv(url)
    species_map = {'setosa': 0, 'versicolor': 1, 'virginica': 2}
    iris_web['target'] = iris_web['species'].map(species_map)
    X3 = iris_web.drop(['species', 'target'], axis=1).values
    y3 = iris_web['target'].values
    print("방법 3 (URL 직접):", X3.shape, y3.shape)
except Exception as e:
    print(f"방법 3 (URL 직접): 네트워크 오류 - {e}")

방법 1 (sklearn 내장): (150, 4) (150,)
방법 2 (csv 저장→읽기): (150, 4) (150,)
방법 3 (URL 직접): (150, 4) (150,)


In [7]:
# ============================================================================
# 2. 학습 및 평가 (방법 1 데이터 사용)
# ============================================================================
X = X1
y = y1

# train/test 분리 (8:2)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# KNN용 스케일링
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

# 모델 정의
models = {
    'Logistic Regression': LogisticRegression(max_iter=5000, random_state=42),
    'Decision Tree':       DecisionTreeClassifier(random_state=42),
    'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42),
    'KNN (k=5)':           KNeighborsClassifier(n_neighbors=5),
}

# 학습 → 예측 → 정확도 + 혼동행렬 출력
print("\n[ Iris - Classification ]")
print("=" * 45)

for name, model in models.items():
    if 'KNN' in name:
        model.fit(X_train_sc, y_train)
        y_pred = model.predict(X_test_sc)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    print(f"\n--- {name} ---")
    print(f"Accuracy : {acc:.4f}")
    print(f"Confusion Matrix:\n{cm}")


[ Iris - Classification ]

--- Logistic Regression ---
Accuracy : 0.9667
Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]

--- Decision Tree ---
Accuracy : 0.9333
Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]

--- Random Forest ---
Accuracy : 0.9000
Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  2  8]]

--- KNN (k=5) ---
Accuracy : 0.9333
Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
