In [18]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
# 데이터 로드 + DataFrame 변환
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target


In [20]:
# X, y 분리
y = df['target']
X = df.drop('target', axis=1)

In [21]:

# 학습 / 테스트 분리 (75% / 25%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [22]:

# ── 1. Logistic Regression ──────────────────────────
clf_lr = LogisticRegression(random_state=0, max_iter=1000)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)

# ── 2. Decision Tree ────────────────────────────────
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)
pred_dt = clf_dt.predict(X_test)

# ── 3. Random Forest ────────────────────────────────
clf_rf = RandomForestClassifier(random_state=0, n_estimators=100)
clf_rf.fit(X_train, y_train)
pred_rf = clf_rf.predict(X_test)


In [23]:

# ── 결과 출력 ────────────────────────────────────────
models = {
    "Logistic Regression": pred_lr,
    "Decision Tree":       pred_dt,
    "Random Forest":       pred_rf,
}

for name, pred in models.items():
    print(f"\n--- {name} ---")
    print(f"Accuracy : {accuracy_score(y_test, pred):.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, pred)}")


--- Logistic Regression ---
Accuracy : 0.9737
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]

--- Decision Tree ---
Accuracy : 0.9737
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]

--- Random Forest ---
Accuracy : 0.9737
Confusion Matrix:
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
# [removed for security]
